### ISSUE TITLE
Design and Add a Logo.

### ISSUE THREAD

**Issue by swapnanildutta** [swapnanildutta/youtube_downloader_executable#11]
Design a logo for this Youtube Downloader and add it to the Title Bar.

**Comment by ngeshlew** [comment]
@swapnanildutta I can take a stab at it if you are interested. Please let me know.

**Comment by swapnanildutta** [comment]
> @swapnanildutta I can take a stab at it if you are interested. Please let me know.

Yeah sure. You're most welcome.

**Comment by ngeshlew** [comment]
Great! Just for context, just have one question that will give me a clear direction on this project.

### Most important question
Which logos resonate with you (especially for this project)? If you want upload them here.

**Comment by swapnanildutta** [comment]
> 
> 
> Great! Just for context, just have one question that will give me a clear direction on this project.
> ### Most important question
> 
> Which logos resonate with you (especially for this project)? If you want upload them here.

Since this is just a basic Youtube Downloader, a basic red logo with downloading symbol would be great. Now it's up to your creativity, you are free to try out stuff.

**Comment by ngeshlew** [comment]
Great! Thanks! Please assign this issue to me @swapnanildutta

**Comment by swapnanildutta** [comment]
Yeah sure. @ngeshlew

**Comment by ngeshlew** [comment]
@swapnanildutta here are the concepts. Please let me know your thoughts.

![ytd-v1](https://user-images.githubusercontent.com/4710827/105747909-70d69480-5f52-11eb-8a3a-fbd706031a83.jpg)
![ytd-v2](https://user-images.githubusercontent.com/4710827/105747925-759b4880-5f52-11eb-81eb-37e8fe97f389.jpg)

**Comment by swapnanildutta** [comment]
The first one's great I feel, quite simple and to the point. The second one's a bit funky.
