### ISSUE TITLE
Enhace the UI using Tkinter and Python3

### ISSUE THREAD

**Issue by swapnanildutta** [swapnanildutta/youtube_downloader_executable#5]

**Comment by RasPiPkr** [comment]
Hi @swapnanildutta,

I was wondering on how you would enhance this GUI as you have not put anything in your issue raised.

Can I offer help in any way?

**Comment by swapnanildutta** [comment]
Yeah sure. I made it using the basic UI, you could better the UI using Tkinter if you can.

**Comment by RasPiPkr** [comment]
Great, I'll fork it now and start to look at making changes.

**Comment by swapnanildutta** [comment]
@RasPiPkr could you add some themes for the background as well?

**Comment by RasPiPkr** [comment]
Do you mean as a picture?

**Comment by swapnanildutta** [comment]
No no, just dark theme and light theme options if possible. Trying to make it a fun Youtube Downloader, not those monotonous ones.

**Comment by RasPiPkr** [comment]
Ok, I will take a look and get back to you on that.

**Comment by swapnanildutta** [comment]
Yeah sure. That would be great.

**Comment by swapnanildutta** [comment]
@RasPiPkr would you like to integrate some more features?

**Comment by RasPiPkr** [comment]
What like?

**Comment by swapnanildutta** [comment]
What more features can be added to a Youtube Video Downloader? Maybe the video details as in Youtube, or some more tabs like adding an About tab menu or something like that. Just innovating the existing one.

**Comment by RasPiPkr** [comment]
ok, leave it with me.

The video details could cause an issue due to the amount of text and would make the window massive but what I could do is show so many characters from the description.

**Comment by swapnanildutta** [comment]
Okay okay. Sure, add as many features as you can. Thank you so much for contributing.

**Comment by RasPiPkr** [comment]
Your welcome :thumbsup:

**Comment by swapnanildutta** [comment]
The Video Thumbnail overlaps the Video Description. @RasPiPkr 

![image](https://user-images.githubusercontent.com/47251193/99869625-ab3e5100-2bf2-11eb-84a0-041e0b871720.png)

**Comment by RasPiPkr** [comment]
Hi,
I didn't make any changes to the layout in this last pull request, how strange.

Q1, was is ok before this pull request and this didn't happen before at all?

Q2, have you tried this video in the previous pull request versions?

I'm going to work now but I'll have a look when I get back.

**Comment by RasPiPkr** [comment]
![noIssue](https://user-images.githubusercontent.com/48888522/99879827-40e3db80-2c07-11eb-90c2-32014e9b2bf5.png)

As you can see above I've tested the same video but I'm not getting any issue.

I think I know the problem, my friend uses a mac and when I've done something for him and he's tried it sometimes the layout looks out. It's down to the difference in the my text and your text format.

What machine are you using as I'm running on linux?
It isn't a big problem, it just needs a text font set for all the text.

**Comment by swapnanildutta** [comment]
I'm using Window 10.

**Comment by RasPiPkr** [comment]
Can this issue be closed off now it's been enhanced?

**Comment by swapnanildutta** [comment]
Just keeping the issue open for others to keep enhancing.
